import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'swiper/swiper-bundle.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content={metadata.description || 'Description'} />
        <title>Code test</title>
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:title" content={metadata.title?.toString() || 'Title'} />
        <meta property="og:description" content={metadata.description || 'Description'} />
        <meta property="og:image" content="/og-image.jpg" />
        <meta property="og:url" content="sites" />
        <meta name="twitter:title" content={metadata.title?.toString() || 'Title'} />
        <meta name="twitter:description" content={metadata.description || 'Description'} />
        <meta name="twitter:image" content="/og-image.jpg" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="robots" content="index, follow" />
      </head>
      <body className={`${inter.className} bg-background text-[#222]`}>
        <Header />

        <main>{children}</main>

        <Footer />
      </body>
    </html>
  )
}
